name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  check-uname1:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: cat /etc/os-release
      - name: 変数受け渡しのテスト
        run: echo $ENVINPUT
        env:
          ENVINPUT: This is Input Strings.
      - name: ファイルをランナーに持っていく
        uses: actions/checkout@v2
      - run: ls -l ./.github/scripts/dayprint.sh
      - name: スクリプトの実行テスト(checkoutが必須)
        run: ./.github/scripts/dayprint.sh
        shell: bash
  check-uname2:
    runs-on: ubuntu-18.04
    steps:
      - run: uname -a
      - run: cat /etc/os-release
