name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  check-uname1:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: cat /etc/os-release
  check-uname2:
    runs-on: ubuntu-18.04
    steps:
      - run: uname -a
      - run: cat /etc/os-release
