name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  check-uname1:
    name: 実行テスト
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: cat /etc/os-release
      - name: 変数受け渡しのテスト
        run: echo $ENVINPUT
        env:
          ENVINPUT: This is Input Strings.
      - name: ファイルをランナーに持っていく
        uses: actions/checkout@v2
      - name: スクリプトの実行テスト(実行権限付与)(checkoutが必須)
        run: |
          chmod u+x ./.github/scripts/dayprint.sh
          ./.github/scripts/dayprint.sh
        shell: bash
      - name: 成果物をファイルに出力（次タスクの前処理）
        shell: bash
        run: expr 1 + 1 > output.log
      - name: 成果物をアップロードする
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
          
  check-uname2:
    runs-on: ubuntu-18.04
    steps:
      - run: uname -a
      - run: cat /etc/os-release
  job2:
    name: 実行テスト２
    runs-on: ubuntu-latest
    needs: check-uname1
    steps:
      - name: 成果物をダウンロードする(別ジョブで作成されたもの)
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
      - name: 成果物を表示
        run: |
          ls -l
          cat output.log
    
